

THORSANVIL_ROOT			= $(realpath ../)
LINK_LIBS				= Json
TARGET					= Serialize.slib
UNITTEST_LINK_LIBS		= Json

JsonSerilizeVardacTest_CXXFLAGS	+= -pedantic -Werror

include ${THORSANVIL_ROOT}/build/tools/Makefile


