#!/bin/bash

#
# Change this as required to point at the root of ThorsAnvil code
FPN=$(pwd)/$0
ROOT=$(dirname $FPN)
THORSANVIL_ROOT=$(dirname ${ROOT})

pushd ${THORSANVIL_ROOT}
git submodule init
git submodule update
build/third/setup
popd


install="sudo apt-get --yes"

host=`uname`
if [[ "${host}" == "Darwin" ]]; then
    # This is a mac use brew
    install="brew"
fi

#
# Need this for building
${install} install bison
${install} install flex
if [[ "${host}" == "Linux" ]]; then
    ${install} install libboost-dev
    ${install} install libboost-doc
fi

